### ISSUE TITLE
textarea required field not recognised as filled

### ISSUE THREAD

**Issue by dygiphy** [strangerstudios/pmpro-register-helper#109]
The following field is not recognised as being completed, despite containing text.  The field is repeatedly cleared on submit, and I receive an error message saying it is required.

Thnx for help

    //define the fields
    $fields = array();
    $fields[] = new PMProRH_Field(
        "Please list the name and date of birth for members you are registering",              // input name, will also be used as meta key
        "textarea",                 // type of field
        array(
            "rows"=>6,         // number of rows to show
            "cols"=>80,         // number of cols to show
            "class"=>"registered_members", // custom class
            "required"=>true,    // make this field required
            "profile"=>true    // show in user profile
        ));

**Comment by dygiphy** [comment]
...actually, I just solved this myself.  I was incorrectly using the input name as a label

    //define the fields
    $fields = array();
    $fields[] = new PMProRH_Field(
        "registered-members",              // input name, will also be used as meta key
        "textarea",                 // type of field
        array(
            "rows"=>6,         // number of rows to show
            "cols"=>80,         // number of cols to show
            "class"=>"registered_members", // custom class
            "profile"=>true,    // show in user profile
            "required"=>true,    // make this field required
            "label"=>"Please list the name and date of birth for members you are registering" //define the label
        ));

**Comment by dparker1005** [comment]
Hi @dygiphy,

I'm glad that you were able to find the solution to the behavior you were experiencing. As this field now appears to be working, I am going to close this Issue.
