### ISSUE TITLE
Custom additional values are bot stored

### ISSUE THREAD

**Issue by maddyBoy** [strangerstudios/pmpro-register-helper#121]
```

function my_pmprorh_init()
{
 
    if (!function_exists('pmprorh_add_registration_field'))
    {   
        return false;
    }


    $fields = array();
    $fields[] = new PMProRH_Field(
        "checkbox_test",         // i am seraching this field in database , there is no such key
        "html",                       // type of field
        array(
            "label"=>"label for the checkbox",
            "html"=>'<input type="checkbox" checked required/>', 
            "profile"=>true 
        ));

   
    foreach($fields as $field)
        pmprorh_add_registration_field(
            "checkout_boxes", // location on checkout page
            $field            // PMProRH_Field object
        );
 }
add_action("init", "my_pmprorh_init");
```

Check box is shown but after successful payment no keys and its values are stored , is there anything else we need to do to save the custom fields values or it save by default ??

Please suggest.
Thank You

**Comment by andrewlimaza** [comment]
Hi there,

What payment gateway are you currently using? 

If you temporarily set the payment gateway to 'Testing Only' do the custom fields save as intended?

**Comment by maddyBoy** [comment]
Thank you for replying !

I am using paypal express in sandbox mode

**Comment by andrewlimaza** [comment]
This sometimes happens from what I've seen, I believe you need to add some additional code to save this in the SESSION when using PayPal Express (I'm not 100% sure why this happens only to some sites with PayPal Express).

It would be similar code to this function I believe - https://gist.github.com/strangerstudios/1894897#file-gistfile1-aw-L248

I am trying to source a code recipe for you, I believe there is one somewhere.

**Comment by eighty20results** [comment]
The 'html' field type isn't intended to have data saved. There's a 'checkbox' field that _will_ be saved. The checkbox field is documented on the Register Helper page: https://www.paidmembershipspro.com/documentation/register-helper-documentation/adding-fields/

**Comment by maddyBoy** [comment]
Actually i want to show dropdown , but trying with this for learning , is there any link (gist) for drop-down code .
Thank You

**Comment by eighty20results** [comment]
In HTML a drop-down is called a "select" box (_all_ of the current HTML input types supported by Register Helper is documented on the page I supplied the link to).

**Comment by maddyBoy** [comment]
Its done , i understood how to do that , now i have drop-downs.

https://gist.github.com/maddyBoy/b78c2f25de094b86c714b5e426c6be2f
