### ISSUE TITLE
If custom field has any of the $public_query_vars naming it doesn't show in profile.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-register-helper#124]
If a custom field has a meta_key value of 'title' for example, it does not show when viewing it in the user's profile.

All other instances seem to work correctly.

I've isolated the code issue to this line -> https://github.com/strangerstudios/pmpro-register-helper/blob/master/classes/class.field.php#L767

**Comment by andrewlimaza** [comment]
Using `$this->meta_key` solves the issue.

**Comment by andrewlimaza** [comment]
Other areas such as displayAtCheckout uses `$this->meta_key` as well.

**Comment by dparker1005** [comment]
Should have been fixed in a previous version.
