### ISSUE TITLE
Should fields with profile set to "only_admin" be visible to users with the "membership_manager" role.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-register-helper#125]
... as added by the pmpro-membership-manager-role add on.

If so, change this line to change if ( ... || current_user_can('pmpro_membership_manager') )

**Comment by andrewlimaza** [comment]
We should support this. I feel the membership_manager should be able to do almost everything an admin can (exclude payment settings) for PMPro and it's Add Ons just without the full WordPress admin options.

**Comment by tictag** [comment]
This issue was raised on the Plus support forum. *MODS ONLY* https://www.paidmembershipspro.com/forums/topic/help-register-helper-addon-some-fields-not-visible-to-membership-manager.

**Comment by ipokkel** [comment]
As a workaround to limit a field's display to administrators and membership managers one may consider switching a field's `profile` option from `only_admin` to `true` using the initially suggested role check.

https://gist.github.com/ipokkel/9f606cc75a6876cd86052745ea391e56

**Comment by dparker1005** [comment]
It may make sense to have `current_user_can('pmpro_membership_manager')` or to make a new capability altogether. It would be nice to be able to make straightforward code recipes to enable/disable this as needed.

**Comment by tictag** [comment]
Whilst Theunis' solution I'm sure works just fine, the way I resolved this issue was to simply wrap the RH field setup in a conditional i.e. the field is only created if the user has the `manage_options` or the `pmpro_membership_manager` capabilities:

```
// only load this on admin pages if you are an admin or membership manager
if ( is_user_logged_in() && is_admin() ) {
	if ( current_user_can ( 'manage_options' ) || current_user_can ( 'pmpro_membership_manager' ) ) {

		$fields   = array();

		$fields[] = new PMProRH_Field(
		...
		'profile => true,
		...
```
This works OK but it would be nice if the `only_admin` parameter actually meant only admin and membership manager when the membership manager addon is installed.
