### ISSUE TITLE
Profile page no longer works

### ISSUE THREAD

**Issue by produktive** [strangerstudios/pmpro-register-helper#129]
I had my system running great until a recent update changed the profile page of my users I believe? It used to be site.com/your-profile/ and now it seems it has changed to just site.com/profile/. Due to this change, my /profile/ page now displays the incorrect template. How can I change the template of my /profile/ page?

**Comment by pbrocks** [comment]
Hi there,

The /your-profile/ slug is likely created Theme My Login, which perhaps you aren't using anymore. For the Profile, are you using our Membership Directory Add On, which creates a /profile/ page.

**Comment by produktive** [comment]
I still am using TML but recently a user complained that the TML profile page just displayed a login prompt. Something changed within TML I believe. I am not using the Membership Directory Add On, the /profile/ page just exists somehow. It's not a page that I can view in my admin panel > pages tab.

**Comment by eighty20results** [comment]
Hi,

Something did indeed change in TML. 

As of version 7.0, the profile page functionality requires a license. You can purchase that license on the TML website: https://thememylogin.com

**Comment by produktive** [comment]
Wow, that's a bummer. I know people gotta eat but we had been using TML for years and now we have to pay for the same functionality we've already been getting? Thanks for the reply.
