### ISSUE TITLE
Text areas do not preserve new lines

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-register-helper#134]
This is because we use `sanitize_text_field` in the function `pmprorh_sanitize()`. Instead for text fields we should be using `sanitize_textarea_field` which preserves whitespace and new lines:

https://developer.wordpress.org/reference/functions/sanitize_textarea_field/

**Comment by bluesteamhost** [comment]
I ran in to this problem today.

This willl require a 2fold solution.  Once the sanitize_textarea_field is applied then wherever you are displaying the output, you need to wrap it in the nl2dr() function to preserve the linebreaks further.

Is there an interim solution without editing the pmpro-register-helper.php plugin file directly??
