### ISSUE TITLE
Bug: The "...fields are required" messages are not translatable.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-register-helper#137]
The "...field(s) is/are required" messages are not translatable.

https://github.com/strangerstudios/pmpro-register-helper/blob/c0be483e7416e30c8e1dc74fadcb145b040d0d48/pmpro-register-helper.php#L656-L659

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/translation-of-error-message-on-checkout-page/

**Comment by andrewlimaza** [comment]
Fixed and releasing in next release :)
