### ISSUE TITLE
Feature Request: Assign class pmpro-required to required fields automatically.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-register-helper#139]
Could we please assign the `.pmpro-required` class automatically to fields having the option `required => true`.

This will make it much easier to target all required fields on the checkout page when using CSS/JS for improved UI/UX or customization.

**Comment by andrewlimaza** [comment]
I got you -> https://github.com/strangerstudios/pmpro-register-helper/pull/171
