### ISSUE TITLE
remove profile_only check

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-register-helper#142]
We settled on "only" as the value for the profile option to show fields only on the profile (and not on checkout) but we still check for "profile_only" here: https://github.com/strangerstudios/pmpro-register-helper/blob/dev/pmpro-register-helper.php#L229

but nowhere else.

Let's remove that extra check.

**Comment by wiethkaty** [comment]
Hello, @ideadude .

Thanks for providing a chance to resolve issue.
Please check and review PR#159.

Thanks.

**Comment by andrewlimaza** [comment]
Thanks for this @wiethkaty, I'll be merging this in shortly :)
