### ISSUE TITLE
Remove Checkout

### ISSUE THREAD

**Issue by myv365** [strangerstudios/pmpro-register-helper#143]
I can not remove or edit a checkout box in the Form Builder.  This box contains 2 items that I do not need.  I did not create it and can not access to remove or edit.  Please help, thank you!

**Comment by myv365** [comment]
![2019-05-12_LI](https://user-images.githubusercontent.com/50561272/57591517-73cbf000-74f7-11e9-80ee-946fc3485e36.jpg)

**Comment by myv365** [comment]
![2019-05-12 (1)_LI](https://user-images.githubusercontent.com/50561272/57591536-86462980-74f7-11e9-8113-9ec0e61b3925.jpg)

**Comment by myv365** [comment]
![2019-05-12 (2)_LI](https://user-images.githubusercontent.com/50561272/57591541-8e9e6480-74f7-11e9-9b8a-8ee905c2ef94.jpg)

**Comment by andrewlimaza** [comment]
This is a different plugin, built by Figarts -> https://figarts.co/product/paid-memberships-pro-form-builder/
