### ISSUE TITLE
Need Help regarding membership plugin

### ISSUE THREAD

**Issue by sajawalkundi** [strangerstudios/pmpro-register-helper#144]
I need help regarding paid membership pro plugin. There are many levels of membership and for free memberships, I want to add 2 additional fields for signup but not for others but when I add 2 fields to checkout page of membership it added to all membership levels. I just want 2 new custom fields to free membership checkout. I also added Register Helper addon but I don't know what to do with this. I am using the Wordpress platform. Any support would be greatly appreciated. Thank you,

**Comment by andrewlimaza** [comment]
Hi @sajawalkundi 

We do not provide support via Github. If you still need assistance with this, please can you open a ticket on www.paidmembershipspro.com

Here is a link to our documentation - https://www.paidmembershipspro.com/add-ons/pmpro-register-helper-add-checkout-and-profile-fields/

Thank you for understanding.
