### ISSUE TITLE
BUG: Required fields for Add Member from Admin not enforced.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-register-helper#149]
When a new member is created in Add Member from Admin the required RH Fields displays but is not checked whether empty on submission of "Add Member".

**Comment by ideadude** [comment]
This is a feature.

If you add a required field after users are already in the system, you don't want admins to have to fill in rubbish when they are just trying to change a user's password/etc.

I'm thinking if it makes sense to either add a new "required even for admins" style feature or maybe something that keeps you from blanking something out. But I really don't agree with doing either of those for admins. Let admins do whatever they want.

Will not fix.
