### ISSUE TITLE
Some field types don't respect the class attribute

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-register-helper#153]
radio buttons, grouped check boxes, and hidden fields should add a class attribute to the main html element in the getHTML method.

https://github.com/strangerstudios/pmpro-register-helper/blob/dev/classes/class.field.php#L403

A work around is to use the divclass property which adds the class to the wrapping div.

**Comment by andrewlimaza** [comment]
Fixed in https://github.com/strangerstudios/pmpro-register-helper/pull/173
