### ISSUE TITLE
Does not support multiple levels in level query string when using MMPU

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-register-helper#154]
When selecting multiple levels for checkout, only the first level in the levels array from the query string is checked when level requirements are specified for a field.

For Example:

if querystring contains `membership-checkout/?level=1+2`and levels specified in field creator as `levels => array( 2, 3 ),` the field is not displayed. 

**Moderators Only:**
https://www.paidmembershipspro.com/forums/topic/signup-questions-not-working/

**Comment by dparker1005** [comment]
I believe the fix for this should just be a matter of updating this code: https://github.com/strangerstudios/pmpro-register-helper/blob/2b8f03394cb5e6a3d82c6a909daf13efcb19d26e/pmpro-register-helper.php#L1163-L1172
