### ISSUE TITLE
Sorry for noob question...

### ISSUE THREAD

**Issue by starfishtrainers** [strangerstudios/pmpro-register-helper#16]
I understand the code and defining teh new elements, what I'm not sure on is where do I place the code?

Does it go in functions.php,  header.php. ??  I really want to make this work.

Please advise.  Thanks.

**Comment by dparker1005** [comment]
We have an article here on how to add PMPro customization code to your site: https://www.paidmembershipspro.com/create-a-plugin-for-pmpro-customizations/

If you have any further questions about this, please feel free to <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> and we would be happy to help you there.
