### ISSUE TITLE
Hook after custom registration fields saved

### ISSUE THREAD

**Issue by ajfick** [strangerstudios/pmpro-register-helper#160]
Is there a hook that will fire after the custom registration fields have been saved? It appears in my testing that `user_register` fires, but before the custom fields have been saved in `usermeta` table.

I've also tried to use the `register_new_user` hook, and one that I found within the code for the pmpro-register-helper plugin called `pmpro_add_member_added`.

I need to be able to access the WP_User along with all of the custom fields within a hook if possible to send off some data to an external service.

Thanks!

**Comment by adeguk** [comment]
I believe this is similar to the same issue I have. I am using Rave payment gateway by flutterwave and I do have some custom fields set up. The custom fields appears on frontend as expected, Rave submits and works well expect that the custom fields (user meta) aint saving. This works with other gateways.

**Comment by andrewlimaza** [comment]
You can temporarily save these fields to session or right before you redirect to your payment gateway.

Here's some example hooks we use to integrate with our supported gateways - https://github.com/strangerstudios/pmpro-register-helper/blob/dev/pmpro-register-helper.php#L531-L535

**Comment by andrewlimaza** [comment]
@adeguk the Rave payment gateway will need to add a similar hook to their code to save the custom fields before redirecting (if they are an offsite gateway).

**Comment by andrewlimaza** [comment]
@ajfick You should be able to hook into `pmpro_after_checkout` to get the user meta values and pass your data through. This will also only reach this hook once a successful checkout occurs.

If you need more support, please reach out on www.paidmembershipspro.com as we usually don't offer support via Github.
