### ISSUE TITLE
SECURITY: select2x2.png and spinner.gif flagged as trojans because they're not images

### ISSUE THREAD

**Issue by noamkfir** [strangerstudios/pmpro-register-helper#163]
These files are being flagged as **trojans** by antivirus software because they're fake images:

- [select2x2.png](https://github.com/strangerstudios/pmpro-register-helper/blob/dev/images/select2x2.png)
- [spinner.gif](https://github.com/strangerstudios/pmpro-register-helper/blob/dev/images/spinner.gif)

The antivirus is flagging them as `Trojan.JS.ImgFake` because they are in fact HTML files and not PNG or GIF files.

I don't know about `spinner.gif` but based on a cursory look at the code, I'm guessing `select2x2.png` should probably have been [ivaynberg's version](https://github.com/ivaynberg/wicket-select2/blob/master/wicket-select2/src/main/java/com/vaynberg/wicket/select2/res/select2x2.png), or removed.

**Comment by andrewlimaza** [comment]
Hi @noamkfir 

Thank you for bringing this to our attention. I have resolved this issue with the latest commit here (I also updated the Select2.js/.css files): https://github.com/strangerstudios/pmpro-register-helper/pull/169/commits/0fa3518903c06673c71bef93a93f41367f009e2e
