### ISSUE TITLE
Notice: Undefined index: member_profile_edit on line 191

### ISSUE THREAD

**Issue by mathieuhays** [strangerstudios/pmpro-register-helper#176]
```
Notice: Undefined index: member_profile_edit in /srv/www/public_html/content/plugins/pmpro-register-helper/pmpro-register-helper.php on line 191
```

I saw a similar notice has been fixed a few hours ago but this one is different.

Thanks :-)

**Comment by DavideWFP** [comment]
`Notice: Undefined index: member_profile_edit in /var/www/vhosts/website.com/httpdocs/wp-content/plugins/pmpro-register-helper/pmpro-register-helper.php on line 191`

after upgrading to latest version

**Comment by andrewlimaza** [comment]
thank you for bringing this to our attention a fix will be released shortly to address this. Please be sure to set `WP_DEBUG` to `false` on your site.

**Comment by andrewlimaza** [comment]
I have just pushed a fix to the `dev` branch, please can you test this version and let me know if it resolves your issue.

Also please include what steps to take to recreate this issue.

**Comment by mathieuhays** [comment]
That fixes it.

Not sure about the steps. My installation is fairly old but the PMPRO plugin is up to date.
The notice shows up on all pages.

I'm not sure how that `member_profile_edit` gets set, it doesn't seem to be part of the base PMPRO installation. As far as I can tell that additional page would be set through the `pmpro_extra_page_settings` filter which is not used in my case.

Disabling any other add-on should allow you to replicate the issue I would imagine.

**Comment by DavideWFP** [comment]
sorry i am a noob so cannot test dev branch (i trust @mathieuhays it works) i will just wait for release.

repro steps in my case is prety straightforward:
1. go to wordpress plugin
2. upgrade the plugin
3. went on site as guest
4. get error warning above header of every page (except membership pages)

**Comment by andrewlimaza** [comment]
Thanks for confirming, the 'member_profile_edit' (front-end profile editing) is coming to version 2.3 of Paid Memberships Pro. We'll be pushing 1.6.1 for Register Helper ASAP to resolve this warning.

**Comment by DavideWFP** [comment]
@andrewlimaza oh thank god! i was about to get another plugin to edit frontend page! when is it coming out?

**Comment by andrewlimaza** [comment]
There's a release candidate already for those wanting to test it and can be downloaded here - https://github.com/strangerstudios/paid-memberships-pro/releases/tag/v2.3-RC1

There's quite a few new features and one of our biggest releases to-date. It should publicly release this week/early next week if no major bugs are found via the RC1 version.
