### ISSUE TITLE
Inability to enter 0 for required fields

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/pmpro-register-helper#177]
If you have a text input that is required, the numeric value of `0` will return `true` if an `empty` function is wrapped around for sanitization.

The line of code in question is: https://github.com/strangerstudios/pmpro-register-helper/blob/dev/pmpro-register-helper.php#L638

Steps to duplicate:

1. Use RH to add a text field and make it required.
2. Enter zero into that field.
3. You will receive a `This field is required` warning message.

The current workaround is to make the numeric fields where a user can enter 0 as not required.

**Comment by ideadude** [comment]
We could change the `empty( $_REQUEST[$field->name] )` part to `isset( $_REQUEST[$field->name] )` but then it would allow blank entries. So we can add `&& trim($_REQUEST[$field->name)) != ''` to make sure there is something there other than white space.

**Comment by dparker1005** [comment]
The issue with comparing the var to `''` is that we do the same check regardless of field type, so it's possible that an array will be passed in the `$_REQUEST`. Instead, going to switch on the field type so that we can do better required checks for each field type.
