### ISSUE TITLE
URL field

### ISSUE THREAD

**Issue by sergeirichard** [strangerstudios/pmpro-register-helper#19]
Hi,

I've created a PMPro form field for a user URL. While the inputted URL appears successfully under "Extra Profile Information", it doesn't populate the standard Website field. This is puzzling as all user name and email fields are successfully transferred. I notice that the input appears in the wp_usermeta table in the database, but not the wp_users table.

However if I open up the user profile page and - without necessarily doing anything else - click "update profile", the data is successfully transferred into the right location. Somehow this completes the process. 

Obviously I don't want to do that with every new user! Is there a way to make sure it goes straight into the user profile automatically? 

Here's the code I wrote. Hopefully I have something wrong... 

$fields[] = new PMProRH_Field("url", "text", array("label"=>"Your Website", "value"=>"http://", "profile"=>true, "class"=>"regular-text"));

It's one of 11 custom fields in an array; the rest work fine.

**Comment by dparker1005** [comment]
We have a code recipe here which shows how you could achieve this behavior:
https://gist.github.com/ipokkel/6590d29c21e41a49e7e2577fe9ca7955

If you have further questions about how to add this behavior to your site, please feel free to <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> and we would be happy to help.

**Comment by sergeirichard** [comment]
Thanks for getting round to this. OK, the site I was building at the time has been shut down for two years now... but on the bright side, I am considering using PMPro for an upcoming project, and knowing that there's a fix for this issue is reassuring. 



was my MSc thesis project, and fortunately I gained a first anyway even though this bug was still in there.
