### ISSUE TITLE
Field Validation

### ISSUE THREAD

**Issue by shiranwp** [strangerstudios/pmpro-register-helper#20]
Hi Guyz,

Does anyone know how to validate fields? I have installed Register Helper, everything works ok but same user with different email can be register. I need to validate members with a field Eg. Membership No.

Please guide this for me

Thanks

**Comment by jbruggeling** [comment]
I'm having a similar problem-  I'm doing my validation in a separate function / custom module. I'm having great difficulty addressing the variables from the custom fields using global.

This contradicts the default included fields which are all setup globally and makes validation really simple.

Can someone please advise how I can custom fields from this module globally

**Comment by dparker1005** [comment]
You can perform validation on your custom fields by using our `pmpro_registration_checks` filter: https://www.paidmembershipspro.com/hook/pmpro_registration_checks/

If you have further questions about this, please feel free to <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> and we would be happy to help you there.
