### ISSUE TITLE
Added extra fields but now showing up in FE but not in Backend

### ISSUE THREAD

**Issue by ghost** [strangerstudios/pmpro-register-helper#26]
I've successfully added extra fields into my signup form and they appear in my signup, as well as in the confirm email, however none of the data is being saved. My code looks like
function my_pmprorh_init()
{
  //don't break if Register Helper is not loaded
  if(!function_exists("pmprorh_add_registration_field"))
  {
    return false;
  }

  //registration level 1 fields
  $fields = array();
  $fields[] = new PMProRH_Field("Degrees and certification", "text", array("size"=>60, "class"=>"degrees", "profile"=>true));
  $fields[] = new PMProRH_Field(" Current school", "text", array("size"=>60, "class"=>"school", "profile"=>true));
  $fields[] = new PMProRH_Field(" Current city and country", "text", array("size"=>60, "class"=>"city", "profile"=>true));
  $fields[] = new PMProRH_Field(" Division at current school", "text", array("size"=>60, "class"=>"division", "profile"=>true));
  $fields[] = new PMProRH_Field(" Past 2-3 schools, city, country", "text", array("size"=>60, "class"=>"past_schools", "profile"=>true));
  $fields[] = new PMProRH_Field(" Nationality ", "text", array("size"=>60, "class"=>"nationality", "profile"=>true));
  $fields[] = new PMProRH_Field(" ", "text", array("size"=>60, "class"=>"nationality", "profile"=>true));
  $fields[] = new PMProRH_Field("Picture", "file", array("profile"=>true, "options"=>array()));

  foreach($fields as $field)
    pmprorh_add_registration_field("checkout_boxes", $field);
    }

add_action("init", "my_pmprorh_init");

But this isn't displaying the the WP backend or in the confirm email, so basically none of these custom meta fields are being stored. What am I missing!?

**Comment by zerotigerds** [comment]
Had the exact same problem. The name of the field can't have spaces or special characters except underscore. If you want it to display with a space use the "label" option in the array where you set things like making it a required field.

**Comment by Petronell** [comment]
I am having this problem - I removed all spaces, still it happens. Any other advise perhaps? 

function my_pmprorh_init()
{
    //don't break if Register Helper is not loaded
    if(!function_exists("pmprorh_add_registration_field"))
    {
        return false;
    }
    //define the fields
  
   $field = array();
$fields[] = new PMProRH_Field("perstitle", "select", array("label"=>"Your Title", "profile"=>"true", "required"=>true, "options"=>array("" => "", "Adv"=>"Adv", "Dr"=>"Dr", "Maj"=>"Maj", "Mr"=>"Mr", "Mrs"=>"Mrs", "Ms"=>"Ms", "Prof"=>"Prof", "Rev"=>"Rev")));
$fields[] = new PMProRH_Field("persprefname", "text", array("label"=>"Preferred Name", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("persfirstname", "text", array("label"=>"First Name", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("perssurname", "text", array("label"=>"Surname", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("persmname", "text", array("label"=>"Maiden Name", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("persidno", "text", array("label"=>"ID Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("persddob", "date", array("label"=>"Date of Birth", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("persprofession", "text", array("label"=>"Profession", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("pershobbies", "textarea", array("label"=>"Hobbies", "rows"=>10, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("perswhere", "select", array("label"=>"How did you find us", "profile"=>"true", "required"=>true, "options"=>array("" => "", "google"=>"google", "ose"=>"other search engine", "wom"=>"word of mouth", "university"=>"university", "college"=>"college", "other"=>"other")));
$fields[] =  new PMProRH_Field("ifother", "textarea", array("label"=>"If Other", "rows"=>10, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("contdet", "html", array("html"=>"", "label"=>"<h3>Other Contact Detail</h3>", "class"=>"company", "profile"=>true));
$fields[] = new PMProRH_Field("conthtel", "text", array("label"=>"Home Telephone Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("contwtel", "text", array("label"=>"Work Telephone Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("contfno", "text", array("label"=>"Fax Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("contcno", "text", array("label"=>"Cellphone Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("contaltmail", "text", array("label"=>"Alternative Email", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));  
$fields[] = new PMProRH_Field("postdet", "html", array("html"=>"", "label"=>"<h3>Postal Address</h3>", "profile"=>true));
$fields[] = new PMProRH_Field("postpbox", "text", array("label"=>"PO Box Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("postbcname", "text", array("label"=>"Building or Complex Name", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("postsnumber", "text", array("label"=>"Street Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("postsname", "text", array("label"=>"Street Name", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("postsuburb", "text", array("label"=>"Suburb", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("postprovince", "text", array("label"=>"Province", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("postcountry", "text", array("label"=>"Country", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("physdet", "html", array("html"=>"", "label"=>"<h3>Physical Address</h3>", "profile"=>true));
$fields[] = new PMProRH_Field("physunumber", "text", array("label"=>"Unit Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("physbcname", "text", array("label"=>"Building or Complex Name", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("physsnumber", "text", array("label"=>"Street Number", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("physsname", "text", array("label"=>"Street Name", "size"=>30, "class"=>"company", "profile"=>true, "required"=>false));
$fields[] = new PMProRH_Field("physsuburb", "text", array("label"=>"Suburb", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("physprovince", "text", array("label"=>"Province", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
$fields[] = new PMProRH_Field("physcountry", "text", array("label"=>"Country", "size"=>30, "class"=>"company", "profile"=>true, "required"=>true));
  
    //add the fields into a new checkout_boxes are of the checkout page
    foreach($fields as $field)
        pmprorh_add_registration_field(
           "checkout_boxes", // location on checkout page
            $field            // PMProRH_Field object
        );
    //that's it. see the PMPro Register Helper readme for more information and examples.
}

add_action("init", "my_pmprorh_init");
