### ISSUE TITLE
add fields to CSV export

### ISSUE THREAD

**Issue by scarchedi** [strangerstudios/pmpro-register-helper#29]
Having trouble getting the fields to be added to the member list export. Here's an example of one of the fields:

$fields[] = new PMProRH_Field("directory", "select", array("options"=>array("" => "", "yes"=>"Yes", "no"=>"No"), "label"=>"Be Included in Our Directory?", "profile"=>true, "memberslistcsv"=>true));

Am I putting it in the wrong place?

**Comment by xueyongg** [comment]
What is the answer to this? @scarchedi Faced this same issue as well @andrewlimaza

**Comment by andrewlimaza** [comment]
@xueyongg you may use `"memberslistcsv"=>true` in your field attributes. If you need support with this do not hesitate to reach out on www.paidmembershipspro.com

**Comment by xueyongg** [comment]
Are we able to still export the data for users who have registered before the field attribute was added?

**Comment by andrewlimaza** [comment]
You can still export data for pre-existing user's but this data may be blank if the user hasn't filled it in on their profile page (if applicable) or renewed their membership.
