### ISSUE TITLE
Error 404 Page Not Found

### ISSUE THREAD

**Issue by OzRedBoy** [strangerstudios/pmpro-register-helper#39]
I already had PMPro installed and activated and I needed more fields added so I have just installed PMPro Register Helper. I followed all the instruction, created the pmpro-customizations.php , edited or added the fields I wanted, viewed the page and everything shows up but once I fill out the form and hit the PayPal checkout (PMPro created pages) I get a "Error 404 Page Not Found", if I deactivated this plugin, then PMPro displays the page with no problems.

I even tried editing the "pmpro-register-helper-fields.php" but that gives me the same error.
I really need help with this problem.

**Comment by strangerstudios** [comment]
OzRedBoy, I'm not sure why that would be happening. Can you share your code to add the fields so I can test on my dev.

If you haven't yet, if you post this our member forums, we should be able to get this fixed up for you ASAP.

**Comment by OzRedBoy** [comment]
To be honest, I changed the code to try other things and since I haven't been able to get it to work and since I hadn't heard anything on here, I just left it and haven't looked at it since.
It's a shame because I really wanted to use both the helper and PMPro.
If I remember what I did, I'll repost but who or how can I get advise to get this (PMPro and helper) to add fields and work correctly?

**Comment by OzRedBoy** [comment]
Sorry for the second post but I found at least the code to add the fields.
I left out the php comment at the start.
/*

Plugin Name: Register Helper Example

Plugin URI: http://www.paidmembershipspro.com/wp/pmpro-customizations/

Description: Register Helper Initialization Example

Version: .1

Author: Stranger Studios

Author URI: http://www.strangerstudios.com

*/

//we have to put everything in a function called on init, so we are sure Register Helper is loaded

function my_pmprorh_init()

{

    //don't break if Register Helper is not loaded

    if(!function_exists("pmprorh_add_registration_field"))

    {

        return false;

    }



    //define the fields

    $fields = array();		
		
	$fields[] = new PMProRH_Field(
        "name",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"=>30,         // input size
            "class"=>"name", // custom class
            "profile"=>true,    // show in user profile
            "required"=>false    // make this field required
        ));	
		
	$fields[] = new PMProRH_Field(
        "surname",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"=>30,         // input size
            "class"=>"surname", // custom class
            "profile"=>true,    // show in user profile
            "required"=>true    // make this field required
        ));	
		
	$fields[] = new PMProRH_Field(
        "phone",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"=>30,         // input size
            "class"=>"phone", // custom class
            "profile"=>true,    // show in user profile
            "required"=>true    // make this field required
        ));	
		
	$fields[] = new PMProRH_Field(
        "house",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"=>10,         // input size
            "class"=>"house", // custom class
            "profile"=>true,    // show in user profile
            "required"=>true    // make this field required
        ));	
		
	$fields[] = new PMProRH_Field(
        "street",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"=>30,         // input size
            "class"=>"street", // custom class
            "profile"=>true,    // show in user profile
            "required"=>true    // make this field required
        ));	
		
	$fields[] = new PMProRH_Field(
        "suburb",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"=>30,         // input size
            "class"=>"suburb", // custom class
            "profile"=>true,    // show in user profile
            "required"=>true    // make this field required
        ));
	
	$fields[] = new PMProRH_Field(
        "postcode",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"=>5,         // input size
            "class"=>"postcode", // custom class
            "profile"=>true,    // show in user profile
            "required"=>true    // make this field required
        ));
	
	$fields[] = new PMProRH_Field(
        "liverpool fc membership no",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"=>30,         // input size
            "class"=>"liverpool_membership", // custom class
            "profile"=>true,    // show in user profile
            "required"=>false    // make this field required
        ));
	
	
	



    //add the fields into a new checkout_boxes are of the checkout page

    foreach($fields as $field)

        pmprorh_add_registration_field(

            "after_email", // location on checkout page

            $field            // PMProRH_Field object

        );



    //that's it. see the PMPro Register Helper readme for more information and examples.

}

add_action("init", "my_pmprorh_init");

Unfortunately I can't remember where and what page I added the other section needed to run it correctly.
If this part of the code is correct, then all I need is help with the remainder of the code placement.
