### ISSUE TITLE
pmprorh_add_checkout_box not working

### ISSUE THREAD

**Issue by dalerodgie** [strangerstudios/pmpro-register-helper#40]
I have been trying to get pmprorh_add_checkout_box to work but can't. Here is my code:

```
function pmpro_application_fields_init()
{
    pmprorh_add_checkout_box(
        "business",
        "Business Information",
        "Fields below are optional but will help us in verifying your account.",
        1
    );

    $field = new PMProRH_Field(
        "company",              // input name, will also be used as meta key
        "text",                 // type of field
        array(
            "size"      => 40,         // input size
            "class"     => "company", // custom class
            "profile"   => true,    // show in user profile
            "required"  => true    // make this field required
        )
    );

    pmprorh_add_registration_field(
        "business", // location on checkout page
        $field            // PMProRH_Field object
    );
}

add_action("init", "pmpro_application_fields_init");
```

Short code on page:

```
[pmpro_signup level="1" intro="Accredited Member" button="Continue"]
```

This is what appears when using ?level=1 in the URL:

![screen shot 2015-02-02 at 6 35 30 am](https://cloud.githubusercontent.com/assets/7511456/5993742/be7e6cde-aaa5-11e4-865d-d458b3c7c5e4.png)

The code works if I use "after_email" in pmprorh_add_registration_field.

Is there something I am missing?

Thanks

**Comment by strangerstudios** [comment]
Sorry to notice this late, but I've just run into this myself. It looks like a recentish update removed some functionality from older versions. I'm working to get everything sorted out and should have an update/fix soon.

**Comment by strangerstudios** [comment]
I just pushed version .6.1 with this fix and some others. Let me know if it's working for you now. Thanks.
