### ISSUE TITLE
Don't use the ucwords() function on labels 

### ISSUE THREAD

**Issue by ejimford** [strangerstudios/pmpro-register-helper#44]
Line 50 of class.field.php and line 129 in pmpro-register-helper.php both apply the ucwords() function the label.
This becomes a problem, in particular, if you are using the html field type.  You don't necessarily want every word of your text to be capitalized.
Also, capitalization is a display-related issue that should be handled by CSS, not by the plugin logic.

**Comment by dparker1005** [comment]
You can prevent `ucwords()` from being run by setting custom lables for your RH fields and checkout boxes in your custom code. That function should only be run if custom labels are not set.

If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
