### ISSUE TITLE
HTML example doesn't work

### ISSUE THREAD

**Issue by osuosu** [strangerstudios/pmpro-register-helper#6]
Hi,

I've tried adding a header in-between my user meta fields, but I get an error of `Unknown type for field`

Here's my code - I'm assuming it's because a field is trying to be created instead of inserting html into the form.

Any ideas? Is this a bug?

Thanks

Osu

```
// CREATE BOX
pmprorh_add_checkout_box("ms", "Membership status");
// FIELDS
$fields4 = array();
$fields4[] = new PMProRH_Field( // Heading
    "pmheading4",
    "html",
    array(
        "html"          =>  "<h3>Membership Status</h3>",
        "profile"       =>  true
        )   
    );
$fields4[] = new PMProRH_Field( // Mailing list
    "ms",
    "select",
    array(
        "class"         =>  "acp-membershipstatus",
        "label"         =>  "Membership Status",
        "profile"       =>  "admins",                   // Only editable by admins
        "options"       =>  array(
            "active"    =>  "Active",
            "np"        =>  "Non-practising",
            "retired"   =>  "Retired")
        )
    );
// LOOP THROUGH FIELDS
foreach($fields4 as $field4) {
    pmprorh_add_registration_field("ms", $field4);
}
```

**Comment by dparker1005** [comment]
Since we have not heard back from you about this issue, we are going to close this ticket. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
