### ISSUE TITLE
Extra field appears on form - but not email sent to Admin or in WP Dashboard

### ISSUE THREAD

**Issue by rockytt** [strangerstudios/pmpro-register-helper#7]
I have a feeling I missed something really basic here - I apologize. I added the code below to the checkout page:

```
$text = new PMProRH_Field("company", "text", array("size"=>40, "class"=>"company", "profile"=>true, "required"=>true));
pmprorh_add_registration_field("after_billing_fields", $text);  
```

And it appears just fine on the form, which submits w/o issue. I do not however, receive the extra form in the email, nor do I see it in the WP Dashboard with the user account. It seems like I'm supposed to add a bit more code somewhere, although I'm not sure exactly what or where. Any guidance would be much appreciated - thanks!

**Comment by zerotigerds** [comment]
Had the exact same problem. The name of the field can't have spaces or special characters except underscore. If you want it to display with a space use the "label" option in the array where you set things like making it a required field.
