### ISSUE TITLE
Dependent fields always required with "select" field type

### ISSUE THREAD

**Issue by mfantini74** [strangerstudios/pmpro-register-helper#70]
All dependent fields are always required with "select" field type, not only the corresponding fields.
If you try to construct a dependent fields with "select" field type, like Country, State, City, and if you need that all fields are required, you cannot register because the hidden fields you didn't chose are require.  

For example:

`
$category = new PMProRH_Field("category", "select", array("required"=>true, "options"=>array("cat1"=>"Category 1", "cat2"=>"Category 2")));  

$subcat1 = new PMProRH_Field("subcat1", "select", array("required"=>true, "options"=>array(1=>"Subcat 1.1", 2=>"Subcat 1.2", 3=>"Subcat 1.3"), "depends"=>array(array("id"=>"category", "value"=>"cat1"))));  

$subcat2 = new PMProRH_Field("subcat2", "select", array("required"=>true, "options"=>array(1=>"Subcat 2.1", 2=>"Subcat 2.2", 3=>"Subcat 2.3"), "depends"=>array(array("id"=>"category", "value"=>"cat2"))));

`

If you choose Category 1 and Subcat 1.2, you cannot register because subcat2 field is required.

Cheers

**Comment by omarabuomar** [comment]
> All dependent fields are always required with "select" field type, not only the corresponding fields.
> If you try to construct a dependent fields with "select" field type, like Country, State, City, and if you need that all fields are required, you cannot register because the hidden fields you didn't chose are require.
> 
> For example:
> 
> `
> $category = new PMProRH_Field("category", "select", array("required"=>true, "options"=>array("cat1"=>"Category 1", "cat2"=>"Category 2")));
> 
> $subcat1 = new PMProRH_Field("subcat1", "select", array("required"=>true, "options"=>array(1=>"Subcat 1.1", 2=>"Subcat 1.2", 3=>"Subcat 1.3"), "depends"=>array(array("id"=>"category", "value"=>"cat1"))));
> 
> $subcat2 = new PMProRH_Field("subcat2", "select", array("required"=>true, "options"=>array(1=>"Subcat 2.1", 2=>"Subcat 2.2", 3=>"Subcat 2.3"), "depends"=>array(array("id"=>"category", "value"=>"cat2"))));
> 
> `
> 
> If you choose Category 1 and Subcat 1.2, you cannot register because subcat2 field is required.
> 
> Cheers

have the same issue, and I believe this is not an idle way to handle this. and even the checkbox option like other option is giving the same error.
Regards,
