### ISSUE TITLE
Variable for a numerical field?

### ISSUE THREAD

**Issue by brytmill** [strangerstudios/pmpro-register-helper#75]
I see $text, $dropdown, $select2, etc. -- but is there a variable for numerical inputs? Ie. "$number" etc.

I tried using $text for an input field that consists of only numbers and when set to required, will not accept numbers in this input field (error validation says the field needs to be filled out).

Anyone else find a solution for this?

Thank you

**Comment by brytmill** [comment]
Anyone have any ideas? I feel like I'm missing something -- there's no way this isn't an option already.

Thanks!

**Comment by dparker1005** [comment]
Hi @brytmill,

Thank you for the suggestion to add this feature. In PMPro Register Helper v1.5, we introduced a `number` field type that has a toggle to increment or decrement the value of the field: https://github.com/strangerstudios/pmpro-register-helper/commit/1d27b114a0625477b9a66c0f9ad0812d08005760

I am going to close this issue as the requested feature has been added, but you run into any issues while using the `number` field type on your site, please let us know by creating a new issue in this GitHub repository.
