### ISSUE TITLE
Required fields throw error message when logged in and invisible

### ISSUE THREAD

**Issue by Mahonyson** [strangerstudios/pmpro-register-helper#91]
Hello. I created required fields in pmpro-register-helper-fields.php and set profile=true. No problem during first registration of a member. But when connected as an existing user these fields throw an error message (Fields required) even as a logged in user will see only the pricing field, level cost and the payment iniformations. Therefore an existing user cannot pay his subscription. No way to bypass this error message even when these required  fields are filled in the profile. Thanks for your help.

WP 4.7.2
Paid Memberships Pro 1.8.13.6
Register Helper 1.3.4

**Comment by andrewlimaza** [comment]
@Mahonyson which checkout box area are you adding the fields to?

**Comment by Mahonyson** [comment]
@andrewlimaza the checkout box area is "after_email". 
I found a workaround by changing the source code of pmpro-register-helper.php. In the filter `add_filter("pmpro_registration_checks", "pmprorh_rf_pmpro_registration_checks");` I tested `if(!is_user_logged_in())` in front of `if(!empty($required))`.

**Comment by andrewlimaza** [comment]
Great stuff! :) 

Thanks for the update, you can also edit the code inside the Register Helper fields code, you can do something similar to -

`if( is_user_logged_in() ){
   $required = false;
}else{
   $required = true;
}`

Then inside your field you could do ` 'required' = $required,`

**Comment by Mahonyson** [comment]
Brilliant! 
Thank you very much!!
