### ISSUE TITLE
Add PMPro billing fields to the edit user profile page Countries Array

### ISSUE THREAD

**Issue by oneminduniv** [strangerstudios/pmpro-register-helper#92]
$fields[] = new PMProRH_Field("pmpro_bcountry", "select", array("label"=>"Billing Country", "profile"=>true, "required"=>false, "options"=>array_merge(array(""=>"- choose one -"), $pmpro_countries)));

This line (select drop down) is showing in the WP profile, but the data is not populating, and the are no options to select.

**Comment by andrewlimaza** [comment]
Hi @oneminduniv you will need to define `global $pmpro_countries` 

I'd recommend to see what value $pmpro_countries is on the edit profile page to ensure this is being passed correctly.

**Comment by oneminduniv** [comment]
The select id="pmpro_bcountry" on the edit profile page.

My logs show this error:

PHP Warning:  array_merge(): Argument #2 is not an array in /home/www/domain.com/wp-content/plugins/add-pmpro-billing-fields-to-the-edit-user-profile-page/add-pmpro-billing-fields-to-the-edit-user-profile-page.php on line 16

Complete plugin code:

`function add_billing_fields_to_profile()
{
	global $pmpro_countries;
	
	//check for register helper
	if(!function_exists("pmprorh_add_registration_field"))
		return;
	
	//define the fields
	$fields = array();
	$fields[] = new PMProRH_Field("pmpro_baddress1", "text", array("label"=>"Billing Address 1", "size"=>40, "profile"=>true, "required"=>false));
	$fields[] = new PMProRH_Field("pmpro_baddress2", "text", array("label"=>"Billing Address 2", "size"=>40, "profile"=>true, "required"=>false));
	$fields[] = new PMProRH_Field("pmpro_bcity", "text", array("label"=>"Billing City", "size"=>40, "profile"=>true, "required"=>false));
	$fields[] = new PMProRH_Field("pmpro_bstate", "text", array("label"=>"Billing State", "size"=>10, "profile"=>true, "required"=>false));
	$fields[] = new PMProRH_Field("pmpro_bzipcode", "text", array("label"=>"Billing Postal Code", "size"=>10, "profile"=>true, "required"=>false));
	$fields[] = new PMProRH_Field("pmpro_bcountry", "select", array("label"=>"Billing Country", "profile"=>true, "required"=>false, "options"=>array_merge(array(""=>"- choose one -"), $pmpro_countries)));
	$fields[] = new PMProRH_Field("pmpro_bphone", "text", array("label"=>"Billing Phone", "size"=>40, "profile"=>true, "required"=>false));	
	
	//add the fields into a new checkout_boxes are of the checkout page
	foreach($fields as $field)
		pmprorh_add_registration_field("profile", $field);
}
add_action("init", "add_billing_fields_to_profile");`
