### ISSUE TITLE
Retain leading zeroes

### ISSUE THREAD

**Issue by neil-ennis** [strangerstudios/pmpro-register-helper#99]
Function pmprorh_sanitize determins the TYPE of field contents implicitly.
This causes problems when you enter digits and don't want to lose leading zeroes, like with phone numbers.
pmprorh_sanitize will recognize the phone number "0722223333" as INTEGER and transform it to "722223333".   Ultimately you will need to implement EXPLICIT types to fix this, but I did this simple hack to work around the problem.

Change FROM this

```
		if ( is_float( $value + 1 ) ) {

			$value = sanitize_text_field( $value );

		}

		if ( is_int( $value + 1 ) ) {

			$value = intval( $value );

		}

```
to this

`		$value = sanitize_text_field( $value );`

**Comment by strangerstudios** [comment]
Last update had a fix for this. Thanks!
